// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/shaned24/tough-notes-storage/internal/pkg/database"
	"github.com/shaned24/tough-notes-storage/internal/pkg/notes"
	"github.com/shaned24/tough-notes-storage/internal/server"
)

// Injectors from inject.go:

func setupServer() (*server.Server, error) {
	config := server.ProvideServerConfig()
	databaseConfig, err := database.ProvideDatabaseConfig()
	if err != nil {
		return nil, err
	}
	client := database.ProvideMongoClient(databaseConfig)
	mongoDbName := database.ProvideMongoDbName()
	mongoCollectionName := database.ProvideMongoCollectionName()
	collection := database.ProvideMongoCollection(client, mongoDbName, mongoCollectionName)
	noteStorage := notes.ProvideNoteStorage(collection)
	noteService := notes.ProvideNoteService(noteStorage)
	databaseDatabase := database.ProvideDatabase(client, databaseConfig)
	serverServer := &server.Server{
		Config:       config,
		NotesService: noteService,
		Database:     databaseDatabase,
	}
	return serverServer, nil
}
