package tests

// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/shaned24/tough-notes-storage/notes/notespb (interfaces: NoteServiceServer)

// Package mock_notespb is a generated GoMock package.

import (
	context "context"
	gomock "github.com/golang/mock/gomock"
	notespb "github.com/shaned24/tough-notes-storage/notes/notespb"
	reflect "reflect"
)

// MockNoteServiceServer is a mock of NoteServiceServer interface
type MockNoteServiceServer struct {
	ctrl     *gomock.Controller
	recorder *MockNoteServiceServerMockRecorder
}

// MockNoteServiceServerMockRecorder is the mock recorder for MockNoteServiceServer
type MockNoteServiceServerMockRecorder struct {
	mock *MockNoteServiceServer
}

// NewMockNoteServiceServer creates a new mock instance
func NewMockNoteServiceServer(ctrl *gomock.Controller) *MockNoteServiceServer {
	mock := &MockNoteServiceServer{ctrl: ctrl}
	mock.recorder = &MockNoteServiceServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockNoteServiceServer) EXPECT() *MockNoteServiceServerMockRecorder {
	return m.recorder
}

// CreateNote mocks base method
func (m *MockNoteServiceServer) CreateNote(arg0 context.Context, arg1 *notespb.CreateNoteRequest) (*notespb.CreateNoteResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateNote", arg0, arg1)
	ret0, _ := ret[0].(*notespb.CreateNoteResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateNote indicates an expected call of CreateNote
func (mr *MockNoteServiceServerMockRecorder) CreateNote(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateNote", reflect.TypeOf((*MockNoteServiceServer)(nil).CreateNote), arg0, arg1)
}

// ReadNote mocks base method
func (m *MockNoteServiceServer) ReadNote(arg0 context.Context, arg1 *notespb.ReadNoteRequest) (*notespb.ReadNoteResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadNote", arg0, arg1)
	ret0, _ := ret[0].(*notespb.ReadNoteResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadNote indicates an expected call of ReadNote
func (mr *MockNoteServiceServerMockRecorder) ReadNote(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadNote", reflect.TypeOf((*MockNoteServiceServer)(nil).ReadNote), arg0, arg1)
}
