// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/shaned24/tough-notes-storage/notes/server/internal/pkg/storage (interfaces: NoteStorage)

// Package tests is a generated GoMock package.
package tests

import (
	context "context"
	gomock "github.com/golang/mock/gomock"
	storage "github.com/shaned24/tough-notes-storage/notes/server/internal/pkg/storage"
	reflect "reflect"
)

// MockNoteStorage is a mock of NoteStorage interface
type MockNoteStorage struct {
	ctrl     *gomock.Controller
	recorder *MockNoteStorageMockRecorder
}

// MockNoteStorageMockRecorder is the mock recorder for MockNoteStorage
type MockNoteStorageMockRecorder struct {
	mock *MockNoteStorage
}

// NewMockNoteStorage creates a new mock instance
func NewMockNoteStorage(ctrl *gomock.Controller) *MockNoteStorage {
	mock := &MockNoteStorage{ctrl: ctrl}
	mock.recorder = &MockNoteStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockNoteStorage) EXPECT() *MockNoteStorageMockRecorder {
	return m.recorder
}

// CreateNote mocks base method
func (m *MockNoteStorage) CreateNote(arg0 context.Context, arg1 *storage.NoteItem) (*storage.NoteItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateNote", arg0, arg1)
	ret0, _ := ret[0].(*storage.NoteItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateNote indicates an expected call of CreateNote
func (mr *MockNoteStorageMockRecorder) CreateNote(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateNote", reflect.TypeOf((*MockNoteStorage)(nil).CreateNote), arg0, arg1)
}

// GetNote mocks base method
func (m *MockNoteStorage) GetNote(arg0 context.Context, arg1 string) (*storage.NoteItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNote", arg0, arg1)
	ret0, _ := ret[0].(*storage.NoteItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNote indicates an expected call of GetNote
func (mr *MockNoteStorageMockRecorder) GetNote(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNote", reflect.TypeOf((*MockNoteStorage)(nil).GetNote), arg0, arg1)
}
