// Code generated by protoc-gen-go. DO NOT EDIT.
// source: notes/notespb/notes.proto

package notespb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Note struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content              string   `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	AuthorId             string   `protobuf:"bytes,4,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Note) Reset()         { *m = Note{} }
func (m *Note) String() string { return proto.CompactTextString(m) }
func (*Note) ProtoMessage()    {}
func (*Note) Descriptor() ([]byte, []int) {
	return fileDescriptor_09d7226a476f5dbc, []int{0}
}

func (m *Note) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Note.Unmarshal(m, b)
}
func (m *Note) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Note.Marshal(b, m, deterministic)
}
func (m *Note) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Note.Merge(m, src)
}
func (m *Note) XXX_Size() int {
	return xxx_messageInfo_Note.Size(m)
}
func (m *Note) XXX_DiscardUnknown() {
	xxx_messageInfo_Note.DiscardUnknown(m)
}

var xxx_messageInfo_Note proto.InternalMessageInfo

func (m *Note) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Note) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Note) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *Note) GetAuthorId() string {
	if m != nil {
		return m.AuthorId
	}
	return ""
}

type CreateNoteRequest struct {
	Note                 *Note    `protobuf:"bytes,1,opt,name=note,proto3" json:"note,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateNoteRequest) Reset()         { *m = CreateNoteRequest{} }
func (m *CreateNoteRequest) String() string { return proto.CompactTextString(m) }
func (*CreateNoteRequest) ProtoMessage()    {}
func (*CreateNoteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_09d7226a476f5dbc, []int{1}
}

func (m *CreateNoteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateNoteRequest.Unmarshal(m, b)
}
func (m *CreateNoteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateNoteRequest.Marshal(b, m, deterministic)
}
func (m *CreateNoteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateNoteRequest.Merge(m, src)
}
func (m *CreateNoteRequest) XXX_Size() int {
	return xxx_messageInfo_CreateNoteRequest.Size(m)
}
func (m *CreateNoteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateNoteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateNoteRequest proto.InternalMessageInfo

func (m *CreateNoteRequest) GetNote() *Note {
	if m != nil {
		return m.Note
	}
	return nil
}

type CreateNoteResponse struct {
	Note                 *Note    `protobuf:"bytes,1,opt,name=note,proto3" json:"note,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateNoteResponse) Reset()         { *m = CreateNoteResponse{} }
func (m *CreateNoteResponse) String() string { return proto.CompactTextString(m) }
func (*CreateNoteResponse) ProtoMessage()    {}
func (*CreateNoteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_09d7226a476f5dbc, []int{2}
}

func (m *CreateNoteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateNoteResponse.Unmarshal(m, b)
}
func (m *CreateNoteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateNoteResponse.Marshal(b, m, deterministic)
}
func (m *CreateNoteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateNoteResponse.Merge(m, src)
}
func (m *CreateNoteResponse) XXX_Size() int {
	return xxx_messageInfo_CreateNoteResponse.Size(m)
}
func (m *CreateNoteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateNoteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateNoteResponse proto.InternalMessageInfo

func (m *CreateNoteResponse) GetNote() *Note {
	if m != nil {
		return m.Note
	}
	return nil
}

type ReadNoteRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadNoteRequest) Reset()         { *m = ReadNoteRequest{} }
func (m *ReadNoteRequest) String() string { return proto.CompactTextString(m) }
func (*ReadNoteRequest) ProtoMessage()    {}
func (*ReadNoteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_09d7226a476f5dbc, []int{3}
}

func (m *ReadNoteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadNoteRequest.Unmarshal(m, b)
}
func (m *ReadNoteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadNoteRequest.Marshal(b, m, deterministic)
}
func (m *ReadNoteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadNoteRequest.Merge(m, src)
}
func (m *ReadNoteRequest) XXX_Size() int {
	return xxx_messageInfo_ReadNoteRequest.Size(m)
}
func (m *ReadNoteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadNoteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadNoteRequest proto.InternalMessageInfo

func (m *ReadNoteRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type ReadNoteResponse struct {
	Note                 *Note    `protobuf:"bytes,1,opt,name=note,proto3" json:"note,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadNoteResponse) Reset()         { *m = ReadNoteResponse{} }
func (m *ReadNoteResponse) String() string { return proto.CompactTextString(m) }
func (*ReadNoteResponse) ProtoMessage()    {}
func (*ReadNoteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_09d7226a476f5dbc, []int{4}
}

func (m *ReadNoteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadNoteResponse.Unmarshal(m, b)
}
func (m *ReadNoteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadNoteResponse.Marshal(b, m, deterministic)
}
func (m *ReadNoteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadNoteResponse.Merge(m, src)
}
func (m *ReadNoteResponse) XXX_Size() int {
	return xxx_messageInfo_ReadNoteResponse.Size(m)
}
func (m *ReadNoteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadNoteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReadNoteResponse proto.InternalMessageInfo

func (m *ReadNoteResponse) GetNote() *Note {
	if m != nil {
		return m.Note
	}
	return nil
}

func init() {
	proto.RegisterType((*Note)(nil), "storage.Note")
	proto.RegisterType((*CreateNoteRequest)(nil), "storage.CreateNoteRequest")
	proto.RegisterType((*CreateNoteResponse)(nil), "storage.CreateNoteResponse")
	proto.RegisterType((*ReadNoteRequest)(nil), "storage.ReadNoteRequest")
	proto.RegisterType((*ReadNoteResponse)(nil), "storage.ReadNoteResponse")
}

func init() { proto.RegisterFile("notes/notespb/notes.proto", fileDescriptor_09d7226a476f5dbc) }

var fileDescriptor_09d7226a476f5dbc = []byte{
	// 262 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x51, 0x3d, 0x4f, 0xc3, 0x40,
	0x0c, 0x55, 0x42, 0x20, 0x8d, 0x2b, 0xbe, 0x2c, 0x86, 0x6b, 0xba, 0xd0, 0x4c, 0x4c, 0x41, 0x2a,
	0x02, 0x46, 0x24, 0x10, 0x03, 0x0b, 0x43, 0xd8, 0x58, 0x50, 0x9a, 0xb3, 0xe0, 0x24, 0x94, 0x0b,
	0x77, 0x2e, 0xff, 0x84, 0xff, 0x8b, 0xe2, 0xa4, 0x1f, 0x6a, 0x3b, 0x74, 0xb9, 0x93, 0xfd, 0xfc,
	0xfc, 0xde, 0x93, 0x61, 0x54, 0x5b, 0x26, 0x7f, 0x2d, 0x6f, 0x33, 0xeb, 0xfe, 0xbc, 0x71, 0x96,
	0x2d, 0xc6, 0x9e, 0xad, 0x2b, 0x3f, 0x29, 0xab, 0x20, 0x7a, 0xb5, 0x4c, 0x78, 0x02, 0xa1, 0xd1,
	0x2a, 0xb8, 0x0c, 0xae, 0x92, 0x22, 0x34, 0x1a, 0x2f, 0xe0, 0x90, 0x0d, 0x7f, 0x93, 0x0a, 0xa5,
	0xd5, 0x15, 0xa8, 0x20, 0xae, 0x6c, 0xcd, 0x54, 0xb3, 0x3a, 0x90, 0xfe, 0xa2, 0xc4, 0x31, 0x24,
	0xe5, 0x9c, 0xbf, 0xac, 0xfb, 0x30, 0x5a, 0x45, 0x82, 0x0d, 0xba, 0xc6, 0x8b, 0xce, 0xee, 0xe0,
	0xfc, 0xc9, 0x51, 0xc9, 0xd4, 0x4a, 0x15, 0xf4, 0x33, 0x27, 0xcf, 0x38, 0x81, 0xa8, 0x75, 0x24,
	0x9a, 0xc3, 0xe9, 0x71, 0xde, 0x3b, 0xca, 0x65, 0x46, 0xa0, 0xec, 0x1e, 0x70, 0x9d, 0xe7, 0x1b,
	0x5b, 0x7b, 0xda, 0x87, 0x38, 0x81, 0xd3, 0x82, 0x4a, 0xbd, 0x2e, 0xb7, 0x11, 0x30, 0xbb, 0x85,
	0xb3, 0xd5, 0xc8, 0xde, 0x9b, 0xa7, 0x7f, 0x01, 0x0c, 0xdb, 0xf2, 0x8d, 0xdc, 0xaf, 0xa9, 0x08,
	0x9f, 0x01, 0x56, 0x16, 0x31, 0x5d, 0x52, 0xb6, 0xf2, 0xa6, 0xe3, 0x9d, 0x58, 0xaf, 0xfc, 0x00,
	0x83, 0x85, 0x1b, 0x54, 0xcb, 0xc1, 0x8d, 0x0c, 0xe9, 0x68, 0x07, 0xd2, 0x2d, 0x78, 0x4c, 0xde,
	0xe3, 0xfe, 0xce, 0xb3, 0x23, 0x39, 0xf1, 0xcd, 0x7f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x82, 0xb1,
	0xef, 0x0a, 0xff, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// NoteServiceClient is the client API for NoteService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type NoteServiceClient interface {
	CreateNote(ctx context.Context, in *CreateNoteRequest, opts ...grpc.CallOption) (*CreateNoteResponse, error)
	ReadNote(ctx context.Context, in *ReadNoteRequest, opts ...grpc.CallOption) (*ReadNoteResponse, error)
}

type noteServiceClient struct {
	cc *grpc.ClientConn
}

func NewNoteServiceClient(cc *grpc.ClientConn) NoteServiceClient {
	return &noteServiceClient{cc}
}

func (c *noteServiceClient) CreateNote(ctx context.Context, in *CreateNoteRequest, opts ...grpc.CallOption) (*CreateNoteResponse, error) {
	out := new(CreateNoteResponse)
	err := c.cc.Invoke(ctx, "/storage.NoteService/CreateNote", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noteServiceClient) ReadNote(ctx context.Context, in *ReadNoteRequest, opts ...grpc.CallOption) (*ReadNoteResponse, error) {
	out := new(ReadNoteResponse)
	err := c.cc.Invoke(ctx, "/storage.NoteService/ReadNote", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NoteServiceServer is the server API for NoteService service.
type NoteServiceServer interface {
	CreateNote(context.Context, *CreateNoteRequest) (*CreateNoteResponse, error)
	ReadNote(context.Context, *ReadNoteRequest) (*ReadNoteResponse, error)
}

func RegisterNoteServiceServer(s *grpc.Server, srv NoteServiceServer) {
	s.RegisterService(&_NoteService_serviceDesc, srv)
}

func _NoteService_CreateNote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateNoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoteServiceServer).CreateNote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/storage.NoteService/CreateNote",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoteServiceServer).CreateNote(ctx, req.(*CreateNoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NoteService_ReadNote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadNoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoteServiceServer).ReadNote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/storage.NoteService/ReadNote",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoteServiceServer).ReadNote(ctx, req.(*ReadNoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _NoteService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "storage.NoteService",
	HandlerType: (*NoteServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateNote",
			Handler:    _NoteService_CreateNote_Handler,
		},
		{
			MethodName: "ReadNote",
			Handler:    _NoteService_ReadNote_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "notes/notespb/notes.proto",
}
