// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/shaned24/tough-notes-storage/notes/server/internal/notes"
	"github.com/shaned24/tough-notes-storage/notes/server/internal/pkg/storage"
)

// Injectors from inject.go:

func setupNoteService() (*notes.NoteService, error) {
	client := storage.NewMongoClient()
	mongoDbName := notes.ProvideMongoDbName()
	mongoCollectionName := notes.ProvideMongoCollectionName()
	collection := notes.ProvideMongoCollection(client, mongoDbName, mongoCollectionName)
	noteStorage := notes.ProvideNoteStorage(client, collection)
	noteService := notes.ProvideNoteService(noteStorage, client)
	return noteService, nil
}
